#title: "CRinnovplusfr"
#description: "Sitio informativo oficial de crinnovplusfr"
author: "DAJP - Tous droits réservés"
theme: jekyll-theme-minimal
url: "https://www.crinnovplusfr.fr"
markdown: kramdown
plugins:
  - jekyll-sitemap
